// Single source of truth for every supported currency.
//
// Both the display metadata (utils/currency.ts -> CURRENCIES) and the offline
// FX seed rates (lib/fx.ts -> SEED_RATES) are derived from this one list so the
// two can never drift apart. Seed rates are approximate "units per 1 EUR" used
// only offline / on first run; the daily live refresh replaces them.
//
// This file intentionally imports nothing, so both fx.ts and currency.ts can
// depend on it without creating an import cycle.

export interface CurrencyDef {
  code: string;
  symbol: string;
  position: 'before' | 'after';
  name: string;
  flag: string;
  seed: number; // approximate units per 1 EUR (offline fallback only)
}

// Ordered: the four main currencies first, then the rest alphabetical by name.
export const CURRENCY_DEFS: CurrencyDef[] = [
  { code: 'EUR', symbol: '€', position: 'after', name: 'Euro', flag: '🇪🇺', seed: 1 },
  { code: 'USD', symbol: '$', position: 'before', name: 'US Dollar', flag: '🇺🇸', seed: 1.08 },
  { code: 'GBP', symbol: '£', position: 'before', name: 'British Pound', flag: '🇬🇧', seed: 0.85 },
  { code: 'AED', symbol: 'AED', position: 'before', name: 'UAE Dirham', flag: '🇦🇪', seed: 3.97 },
  { code: 'AFN', symbol: 'AFN', position: 'before', name: 'Afghan Afghani', flag: '🇦🇫', seed: 76 },
  { code: 'ALL', symbol: 'L', position: 'after', name: 'Albanian Lek', flag: '🇦🇱', seed: 99 },
  { code: 'DZD', symbol: 'DA', position: 'before', name: 'Algerian Dinar', flag: '🇩🇿', seed: 145 },
  { code: 'AOA', symbol: 'Kz', position: 'before', name: 'Angolan Kwanza', flag: '🇦🇴', seed: 990 },
  { code: 'ARS', symbol: '$', position: 'before', name: 'Argentine Peso', flag: '🇦🇷', seed: 1090 },
  { code: 'AMD', symbol: '֏', position: 'before', name: 'Armenian Dram', flag: '🇦🇲', seed: 420 },
  { code: 'AWG', symbol: 'ƒ', position: 'before', name: 'Aruban Florin', flag: '🇦🇼', seed: 1.94 },
  { code: 'AUD', symbol: '$', position: 'before', name: 'Australian Dollar', flag: '🇦🇺', seed: 1.63 },
  { code: 'AZN', symbol: '₼', position: 'before', name: 'Azerbaijani Manat', flag: '🇦🇿', seed: 1.84 },
  { code: 'BSD', symbol: '$', position: 'before', name: 'Bahamian Dollar', flag: '🇧🇸', seed: 1.08 },
  { code: 'BHD', symbol: 'BHD', position: 'before', name: 'Bahraini Dinar', flag: '🇧🇭', seed: 0.41 },
  { code: 'BDT', symbol: '৳', position: 'before', name: 'Bangladeshi Taka', flag: '🇧🇩', seed: 128 },
  { code: 'BBD', symbol: '$', position: 'before', name: 'Barbadian Dollar', flag: '🇧🇧', seed: 2.16 },
  { code: 'BYN', symbol: 'Br', position: 'before', name: 'Belarusian Ruble', flag: '🇧🇾', seed: 3.53 },
  { code: 'BZD', symbol: '$', position: 'before', name: 'Belize Dollar', flag: '🇧🇿', seed: 2.17 },
  { code: 'BMD', symbol: '$', position: 'before', name: 'Bermudan Dollar', flag: '🇧🇲', seed: 1.08 },
  { code: 'BTN', symbol: 'Nu.', position: 'before', name: 'Bhutanese Ngultrum', flag: '🇧🇹', seed: 90 },
  { code: 'BOB', symbol: 'Bs', position: 'before', name: 'Bolivian Boliviano', flag: '🇧🇴', seed: 7.5 },
  { code: 'BAM', symbol: 'KM', position: 'after', name: 'Bosnia-Herzegovina Convertible Mark', flag: '🇧🇦', seed: 1.96 },
  { code: 'BWP', symbol: 'P', position: 'before', name: 'Botswanan Pula', flag: '🇧🇼', seed: 14.8 },
  { code: 'BRL', symbol: 'R$', position: 'before', name: 'Brazilian Real', flag: '🇧🇷', seed: 5.9 },
  { code: 'BND', symbol: '$', position: 'before', name: 'Brunei Dollar', flag: '🇧🇳', seed: 1.46 },
  { code: 'BGN', symbol: 'лв', position: 'after', name: 'Bulgarian Lev', flag: '🇧🇬', seed: 1.96 },
  { code: 'BIF', symbol: 'FBu', position: 'before', name: 'Burundian Franc', flag: '🇧🇮', seed: 3150 },
  { code: 'KHR', symbol: '៛', position: 'before', name: 'Cambodian Riel', flag: '🇰🇭', seed: 4400 },
  { code: 'CAD', symbol: '$', position: 'before', name: 'Canadian Dollar', flag: '🇨🇦', seed: 1.47 },
  { code: 'CVE', symbol: 'CVE', position: 'before', name: 'Cape Verdean Escudo', flag: '🇨🇻', seed: 110 },
  { code: 'KYD', symbol: '$', position: 'before', name: 'Cayman Islands Dollar', flag: '🇰🇾', seed: 0.9 },
  { code: 'XAF', symbol: 'FCFA', position: 'before', name: 'Central African CFA Franc', flag: '🇨🇲', seed: 655.96 },
  { code: 'XPF', symbol: '₣', position: 'before', name: 'CFP Franc', flag: '🇵🇫', seed: 119.33 },
  { code: 'CLP', symbol: '$', position: 'before', name: 'Chilean Peso', flag: '🇨🇱', seed: 1040 },
  { code: 'CNY', symbol: '¥', position: 'before', name: 'Chinese Yuan', flag: '🇨🇳', seed: 7.8 },
  { code: 'COP', symbol: '$', position: 'before', name: 'Colombian Peso', flag: '🇨🇴', seed: 4400 },
  { code: 'KMF', symbol: 'CF', position: 'before', name: 'Comorian Franc', flag: '🇰🇲', seed: 492 },
  { code: 'CDF', symbol: 'FC', position: 'before', name: 'Congolese Franc', flag: '🇨🇩', seed: 3050 },
  { code: 'CRC', symbol: '₡', position: 'before', name: 'Costa Rican Colón', flag: '🇨🇷', seed: 550 },
  { code: 'CUP', symbol: '$', position: 'before', name: 'Cuban Peso', flag: '🇨🇺', seed: 26 },
  { code: 'CZK', symbol: 'Kč', position: 'after', name: 'Czech Koruna', flag: '🇨🇿', seed: 25 },
  { code: 'DKK', symbol: 'kr', position: 'after', name: 'Danish Krone', flag: '🇩🇰', seed: 7.46 },
  { code: 'DJF', symbol: 'Fdj', position: 'before', name: 'Djiboutian Franc', flag: '🇩🇯', seed: 192 },
  { code: 'DOP', symbol: 'RD$', position: 'before', name: 'Dominican Peso', flag: '🇩🇴', seed: 65 },
  { code: 'XCD', symbol: '$', position: 'before', name: 'East Caribbean Dollar', flag: '🇱🇨', seed: 2.92 },
  { code: 'EGP', symbol: 'E£', position: 'before', name: 'Egyptian Pound', flag: '🇪🇬', seed: 52 },
  { code: 'ERN', symbol: 'Nfk', position: 'before', name: 'Eritrean Nakfa', flag: '🇪🇷', seed: 16.2 },
  { code: 'ETB', symbol: 'Br', position: 'before', name: 'Ethiopian Birr', flag: '🇪🇹', seed: 130 },
  { code: 'FKP', symbol: '£', position: 'before', name: 'Falkland Islands Pound', flag: '🇫🇰', seed: 0.85 },
  { code: 'FJD', symbol: '$', position: 'before', name: 'Fijian Dollar', flag: '🇫🇯', seed: 2.44 },
  { code: 'GMD', symbol: 'D', position: 'before', name: 'Gambian Dalasi', flag: '🇬🇲', seed: 76 },
  { code: 'GEL', symbol: '₾', position: 'before', name: 'Georgian Lari', flag: '🇬🇪', seed: 2.95 },
  { code: 'GHS', symbol: '₵', position: 'before', name: 'Ghanaian Cedi', flag: '🇬🇭', seed: 16.5 },
  { code: 'GIP', symbol: '£', position: 'before', name: 'Gibraltar Pound', flag: '🇬🇮', seed: 0.85 },
  { code: 'GTQ', symbol: 'Q', position: 'before', name: 'Guatemalan Quetzal', flag: '🇬🇹', seed: 8.4 },
  { code: 'GNF', symbol: 'FG', position: 'before', name: 'Guinean Franc', flag: '🇬🇳', seed: 9350 },
  { code: 'GYD', symbol: '$', position: 'before', name: 'Guyanaese Dollar', flag: '🇬🇾', seed: 226 },
  { code: 'HTG', symbol: 'G', position: 'before', name: 'Haitian Gourde', flag: '🇭🇹', seed: 143 },
  { code: 'HNL', symbol: 'L', position: 'before', name: 'Honduran Lempira', flag: '🇭🇳', seed: 27 },
  { code: 'HKD', symbol: '$', position: 'before', name: 'Hong Kong Dollar', flag: '🇭🇰', seed: 8.45 },
  { code: 'HUF', symbol: 'Ft', position: 'after', name: 'Hungarian Forint', flag: '🇭🇺', seed: 396 },
  { code: 'ISK', symbol: 'kr', position: 'after', name: 'Icelandic Króna', flag: '🇮🇸', seed: 150 },
  { code: 'INR', symbol: '₹', position: 'before', name: 'Indian Rupee', flag: '🇮🇳', seed: 90 },
  { code: 'IDR', symbol: 'Rp', position: 'before', name: 'Indonesian Rupiah', flag: '🇮🇩', seed: 17200 },
  { code: 'IRR', symbol: 'IRR', position: 'before', name: 'Iranian Rial', flag: '🇮🇷', seed: 45500 },
  { code: 'IQD', symbol: 'IQD', position: 'before', name: 'Iraqi Dinar', flag: '🇮🇶', seed: 1420 },
  { code: 'ILS', symbol: '₪', position: 'before', name: 'Israeli Shekel', flag: '🇮🇱', seed: 4 },
  { code: 'JMD', symbol: '$', position: 'before', name: 'Jamaican Dollar', flag: '🇯🇲', seed: 170 },
  { code: 'JPY', symbol: '¥', position: 'before', name: 'Japanese Yen', flag: '🇯🇵', seed: 170 },
  { code: 'JOD', symbol: 'JOD', position: 'before', name: 'Jordanian Dinar', flag: '🇯🇴', seed: 0.77 },
  { code: 'KZT', symbol: '₸', position: 'before', name: 'Kazakhstani Tenge', flag: '🇰🇿', seed: 540 },
  { code: 'KES', symbol: 'KSh', position: 'before', name: 'Kenyan Shilling', flag: '🇰🇪', seed: 140 },
  { code: 'KWD', symbol: 'KWD', position: 'before', name: 'Kuwaiti Dinar', flag: '🇰🇼', seed: 0.33 },
  { code: 'KGS', symbol: 'KGS', position: 'before', name: 'Kyrgystani Som', flag: '🇰🇬', seed: 94 },
  { code: 'LAK', symbol: '₭', position: 'before', name: 'Laotian Kip', flag: '🇱🇦', seed: 23600 },
  { code: 'LBP', symbol: 'LBP', position: 'before', name: 'Lebanese Pound', flag: '🇱🇧', seed: 96500 },
  { code: 'LSL', symbol: 'L', position: 'before', name: 'Lesotho Loti', flag: '🇱🇸', seed: 20 },
  { code: 'LRD', symbol: '$', position: 'before', name: 'Liberian Dollar', flag: '🇱🇷', seed: 210 },
  { code: 'LYD', symbol: 'LYD', position: 'before', name: 'Libyan Dinar', flag: '🇱🇾', seed: 5.2 },
  { code: 'MOP', symbol: 'MOP$', position: 'before', name: 'Macanese Pataca', flag: '🇲🇴', seed: 8.7 },
  { code: 'MKD', symbol: 'ден', position: 'after', name: 'Macedonian Denar', flag: '🇲🇰', seed: 61.5 },
  { code: 'MGA', symbol: 'Ar', position: 'before', name: 'Malagasy Ariary', flag: '🇲🇬', seed: 4950 },
  { code: 'MWK', symbol: 'MK', position: 'before', name: 'Malawian Kwacha', flag: '🇲🇼', seed: 1880 },
  { code: 'MYR', symbol: 'RM', position: 'before', name: 'Malaysian Ringgit', flag: '🇲🇾', seed: 5.1 },
  { code: 'MVR', symbol: 'Rf', position: 'before', name: 'Maldivian Rufiyaa', flag: '🇲🇻', seed: 16.7 },
  { code: 'MRU', symbol: 'UM', position: 'before', name: 'Mauritanian Ouguiya', flag: '🇲🇷', seed: 43 },
  { code: 'MUR', symbol: 'Rs', position: 'before', name: 'Mauritian Rupee', flag: '🇲🇺', seed: 50 },
  { code: 'MXN', symbol: '$', position: 'before', name: 'Mexican Peso', flag: '🇲🇽', seed: 20 },
  { code: 'MDL', symbol: 'L', position: 'after', name: 'Moldovan Leu', flag: '🇲🇩', seed: 19.3 },
  { code: 'MNT', symbol: '₮', position: 'before', name: 'Mongolian Tugrik', flag: '🇲🇳', seed: 3700 },
  { code: 'MAD', symbol: 'MAD', position: 'before', name: 'Moroccan Dirham', flag: '🇲🇦', seed: 10.8 },
  { code: 'MZN', symbol: 'MT', position: 'before', name: 'Mozambican Metical', flag: '🇲🇿', seed: 69 },
  { code: 'MMK', symbol: 'K', position: 'before', name: 'Myanmar Kyat', flag: '🇲🇲', seed: 2270 },
  { code: 'NAD', symbol: '$', position: 'before', name: 'Namibian Dollar', flag: '🇳🇦', seed: 20 },
  { code: 'NPR', symbol: 'Rs', position: 'before', name: 'Nepalese Rupee', flag: '🇳🇵', seed: 144 },
  { code: 'ANG', symbol: 'ƒ', position: 'before', name: 'Netherlands Antillean Guilder', flag: '🇨🇼', seed: 1.94 },
  { code: 'TWD', symbol: 'NT$', position: 'before', name: 'New Taiwan Dollar', flag: '🇹🇼', seed: 35 },
  { code: 'NZD', symbol: '$', position: 'before', name: 'New Zealand Dollar', flag: '🇳🇿', seed: 1.78 },
  { code: 'NIO', symbol: 'C$', position: 'before', name: 'Nicaraguan Córdoba', flag: '🇳🇮', seed: 40 },
  { code: 'NGN', symbol: '₦', position: 'before', name: 'Nigerian Naira', flag: '🇳🇬', seed: 1750 },
  { code: 'NOK', symbol: 'kr', position: 'after', name: 'Norwegian Krone', flag: '🇳🇴', seed: 11.7 },
  { code: 'OMR', symbol: 'OMR', position: 'before', name: 'Omani Rial', flag: '🇴🇲', seed: 0.42 },
  { code: 'PKR', symbol: 'Rs', position: 'before', name: 'Pakistani Rupee', flag: '🇵🇰', seed: 300 },
  { code: 'PAB', symbol: 'B/.', position: 'before', name: 'Panamanian Balboa', flag: '🇵🇦', seed: 1.08 },
  { code: 'PGK', symbol: 'K', position: 'before', name: 'Papua New Guinean Kina', flag: '🇵🇬', seed: 4.3 },
  { code: 'PYG', symbol: '₲', position: 'before', name: 'Paraguayan Guarani', flag: '🇵🇾', seed: 8450 },
  { code: 'PEN', symbol: 'S/', position: 'before', name: 'Peruvian Sol', flag: '🇵🇪', seed: 4.05 },
  { code: 'PHP', symbol: '₱', position: 'before', name: 'Philippine Peso', flag: '🇵🇭', seed: 62 },
  { code: 'PLN', symbol: 'zł', position: 'after', name: 'Polish Złoty', flag: '🇵🇱', seed: 4.3 },
  { code: 'QAR', symbol: 'QAR', position: 'before', name: 'Qatari Riyal', flag: '🇶🇦', seed: 3.93 },
  { code: 'RON', symbol: 'lei', position: 'after', name: 'Romanian Leu', flag: '🇷🇴', seed: 4.97 },
  { code: 'RUB', symbol: '₽', position: 'after', name: 'Russian Ruble', flag: '🇷🇺', seed: 100 },
  { code: 'RWF', symbol: 'FRw', position: 'before', name: 'Rwandan Franc', flag: '🇷🇼', seed: 1480 },
  { code: 'SHP', symbol: '£', position: 'before', name: 'Saint Helena Pound', flag: '🇸🇭', seed: 0.85 },
  { code: 'WST', symbol: 'WS$', position: 'before', name: 'Samoan Tala', flag: '🇼🇸', seed: 2.96 },
  { code: 'STN', symbol: 'Db', position: 'before', name: 'São Tomé & Príncipe Dobra', flag: '🇸🇹', seed: 24.5 },
  { code: 'SAR', symbol: 'SAR', position: 'before', name: 'Saudi Riyal', flag: '🇸🇦', seed: 4.05 },
  { code: 'RSD', symbol: 'дин', position: 'after', name: 'Serbian Dinar', flag: '🇷🇸', seed: 117 },
  { code: 'SCR', symbol: 'Rs', position: 'before', name: 'Seychellois Rupee', flag: '🇸🇨', seed: 15 },
  { code: 'SLE', symbol: 'Le', position: 'before', name: 'Sierra Leonean Leone', flag: '🇸🇱', seed: 24.5 },
  { code: 'SGD', symbol: '$', position: 'before', name: 'Singapore Dollar', flag: '🇸🇬', seed: 1.46 },
  { code: 'SBD', symbol: '$', position: 'before', name: 'Solomon Islands Dollar', flag: '🇸🇧', seed: 9.2 },
  { code: 'SOS', symbol: 'Sh', position: 'before', name: 'Somali Shilling', flag: '🇸🇴', seed: 617 },
  { code: 'ZAR', symbol: 'R', position: 'before', name: 'South African Rand', flag: '🇿🇦', seed: 20 },
  { code: 'KRW', symbol: '₩', position: 'before', name: 'South Korean Won', flag: '🇰🇷', seed: 1470 },
  { code: 'SSP', symbol: 'SSP', position: 'before', name: 'South Sudanese Pound', flag: '🇸🇸', seed: 1600 },
  { code: 'LKR', symbol: 'Rs', position: 'before', name: 'Sri Lankan Rupee', flag: '🇱🇰', seed: 320 },
  { code: 'SDG', symbol: 'SDG', position: 'before', name: 'Sudanese Pound', flag: '🇸🇩', seed: 650 },
  { code: 'SRD', symbol: '$', position: 'before', name: 'Surinamese Dollar', flag: '🇸🇷', seed: 38 },
  { code: 'SZL', symbol: 'L', position: 'before', name: 'Swazi Lilangeni', flag: '🇸🇿', seed: 20 },
  { code: 'SEK', symbol: 'kr', position: 'after', name: 'Swedish Krona', flag: '🇸🇪', seed: 11.4 },
  { code: 'CHF', symbol: 'CHF', position: 'before', name: 'Swiss Franc', flag: '🇨🇭', seed: 0.96 },
  { code: 'SYP', symbol: 'SYP', position: 'before', name: 'Syrian Pound', flag: '🇸🇾', seed: 14000 },
  { code: 'TJS', symbol: 'SM', position: 'before', name: 'Tajikistani Somoni', flag: '🇹🇯', seed: 11.8 },
  { code: 'TZS', symbol: 'TSh', position: 'before', name: 'Tanzanian Shilling', flag: '🇹🇿', seed: 2900 },
  { code: 'THB', symbol: '฿', position: 'before', name: 'Thai Baht', flag: '🇹🇭', seed: 39 },
  { code: 'TOP', symbol: 'T$', position: 'before', name: 'Tongan Paʻanga', flag: '🇹🇴', seed: 2.56 },
  { code: 'TTD', symbol: '$', position: 'before', name: 'Trinidad & Tobago Dollar', flag: '🇹🇹', seed: 7.3 },
  { code: 'TND', symbol: 'DT', position: 'before', name: 'Tunisian Dinar', flag: '🇹🇳', seed: 3.4 },
  { code: 'TRY', symbol: '₺', position: 'before', name: 'Turkish Lira', flag: '🇹🇷', seed: 35 },
  { code: 'TMT', symbol: 'TMT', position: 'before', name: 'Turkmenistani Manat', flag: '🇹🇲', seed: 3.8 },
  { code: 'UGX', symbol: 'USh', position: 'before', name: 'Ugandan Shilling', flag: '🇺🇬', seed: 4050 },
  { code: 'UAH', symbol: '₴', position: 'before', name: 'Ukrainian Hryvnia', flag: '🇺🇦', seed: 44 },
  { code: 'UYU', symbol: '$U', position: 'before', name: 'Uruguayan Peso', flag: '🇺🇾', seed: 43 },
  { code: 'UZS', symbol: 'UZS', position: 'before', name: 'Uzbekistani Som', flag: '🇺🇿', seed: 13800 },
  { code: 'VUV', symbol: 'VT', position: 'before', name: 'Vanuatu Vatu', flag: '🇻🇺', seed: 129 },
  { code: 'VES', symbol: 'Bs', position: 'before', name: 'Venezuelan Bolívar', flag: '🇻🇪', seed: 44 },
  { code: 'VND', symbol: '₫', position: 'after', name: 'Vietnamese Dong', flag: '🇻🇳', seed: 27200 },
  { code: 'XOF', symbol: 'CFA', position: 'before', name: 'West African CFA Franc', flag: '🇸🇳', seed: 655.96 },
  { code: 'YER', symbol: 'YER', position: 'before', name: 'Yemeni Rial', flag: '🇾🇪', seed: 270 },
  { code: 'ZMW', symbol: 'ZK', position: 'before', name: 'Zambian Kwacha', flag: '🇿🇲', seed: 29 },
];
